config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, :customers, :projects, :tasks
  resources :task_entries do 
    put '/start', to: 'task_entries#start_now'
    put '/stop', to: 'task_entries#stop_now'
  end
end

app/models/task_entry.rb
class TaskEntry < ApplicationRecord
  belongs_to :task
  validates :task_id, presence: true
  validates :note, presence: true, length: { maximum: 1000 }
  # after_initialize :set_duration

  # def updated_at=(value)
  #   self[:updated_at] = value
  #   set_duration
  # end

  # def start_time=(value)
  #   self[:start_time] = value
  #   set_duration
  # end

  # def set_duration()
  #   self[:duration] = calculate_duration
  # end

  # private
  # def calculate_duration
  #   (updated_at && start_time) ? (updated_at - start_time).to_i : nil
  # end
end

app/controllers/task_entries_controller.rb
class TaskEntriesController < ApplicationController
    before_action :logged_in_user

    def initialize 
        super
        @resource = "Task Entries"
      end

    # CREATE
    def create 
        @task_entry = TaskEntry.new(task_entry_params)
        if @task_entry.save
        flash[:success] = "Created task entry"
        redirect_to @task_entry
        else
        render :new
        end 
    end

    def new
        @task_entry = TaskEntry.new if @task_entry == nil
        @task_options = Task.all.map{|t|[t.task_name, t.id]}
    end

    # READ
    def index 
        @task_entries = TaskEntry.joins(:task).where("tasks.user_id = ?", current_user.id).paginate(page: params[:page], :per_page => 10)
        
        @total_duration = @task_entries.map do |task_entry|
            task_entry.duration.present? ? task_entry.duration : 0
        end.sum
    end

    def show 
        @task_entry = TaskEntry.find(params[:id])
    end

    # UPDATE
    def update
        @task_entry = TaskEntry.find(params[:id])
        if @task_entry.update_attributes(task_entry_params)
            flash[:success] = "Updated task entry"
            redirect_to @task_entry
        else
            render 'edit'
        end
    end

    def edit 
        @task_entry = TaskEntry.find(params[:id])
    end 
    
    # DESTROY
    def destroy
        TaskEntry.find(params[:id]).destroy
        flash[:success] = "Deleted task entry"
        redirect_to task_entries_url
    end

    def start_now
      @task_entry = TaskEntry.find(params[:task_entry_id])
      @task_entry.start_time = Time.now
      @task_entry.save
      flash[:success] = "Started timer"
      redirect_to task_entries_url
    end

    def stop_now
      @task_entry = TaskEntry.find(params[:task_entry_id])
      @task_entry.duration = (Time.now - @task_entry.start_time)/60
      @task_entry.save
      flash[:success] = "Stop timer"
      redirect_to task_entries_url
    end

    private 
    def task_entry_params 
      params.require(:task_entry).permit(:note, :start_time, :task_id, :duration)
    end
end

app/helpers/task_entries_helper.rb
module TaskEntriesHelper
end

app/views/task_entries/_task_entry.erb
<li id="task_entry-<%= task_entry.id %>">
    <span class="task_entry_name">
        <a href="/task_entries/<%= task_entry.id %>">
            <%= task_entry.note %>
        </a>
    </span>
</li>

app/views/task_entries/edit.html.erb
<% provide(:title, 'Edit Task Entry') %>
<h1>Edit Task Entry</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@task_entry) do |f| %>
            <%= render 'shared/error_messages', :@profile => @task_entry %>

            <%= f.label :note %>
            <%= f.text_field :note, class: 'form-control'%>

            <%= f.label :start_time %>
            <%= f.text_field :start_time, class: 'form-control'%>

            <%= f.label :duration %><span> (minutes)</span>
            <%= f.text_field :duration, class: 'form-control'%>

            <%= f.submit "Save changes", class: "btn btn-primary form-button-create" %>
        <% end %>
    </div>
</div>

app/views/task_entries/index.html.erb
<% provide(:title, 'Task Entries') %>
<div class="container resources-container">
    <h1>Task Entries</h1>
    <%= render 'shared/paginate', :@profile => @task_entries%>
    <ul class="resources resources-grid">
        <li class="center">Notes</li>
        <li class="center">Duration (minutes)</li>
        <li class="center">Start Time</li>
        <li class="center">Stop Time</li>
        <% @task_entries.each do |task_entry| %>
            <li class="center">
                <%= link_to task_entry.note, task_entry %>
            </li>
            <li class="center"> 
                <% if task_entry.start_time && !task_entry.duration%>
                    <p>Ongoing</p>
                <% else %>
                    <%= task_entry.duration%>
                <% end %>
            </li>
            <li class="center">
                <% if task_entry.start_time%>
                    <%= task_entry.start_time%>
                <% else %>
                    <div class="<%= task_entry.start_time ? "hidden" : ""%>">
                        <%= form_for(task_entry, url: task_entry_start_path(task_entry), method: :put) do |f|%>
                            <% f.submit "Start Now", class:"btn btn-primary sm"%>
                        <% end%>
                    </div>
                <% end %>
            </li>

            <li class="center">
                <% if task_entry.start_time && !task_entry.duration%>
                    <%= form_for(task_entry, url: task_entry_stop_path(task_entry), method: :put) do |f|%>
                    <% f.submit "Stop Now", class:"btn btn-primary sm"%>
                    <% end%>
                <% end %>
            </li>
        <% end %>
    </ul>
    <section class="center total-duration">
      <span>Total Duration: </span> <%= @total_duration %> minutes
    </section>
    <%= render 'shared/paginate', :@profile => @task_entries%>
    <div class="center">
        <%= link_to "Create Task Entry", new_task_entry_path, class: "btn btn-lg btn-primary" %>
    </div>
</div>

app/views/task_entries/new.html.erb
<% provide(:title, 'Create Task Entry') %>
<h1>Create Task Entry</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task_entry) do |f| %>
      <%= render 'shared/error_messages', :@profile => @task_entry %>

      <%= f.label :note %>
      <%= f.text_field :note, class: 'form-control'%>

      <%= f.label :task %>
      <%= f.select :task_id, Task.where(user_id: current_user.id).collect{|t|[t.task_name, t.id]},{}, { :class => "form-control" }%>

      <%= f.submit "Create task entry", class: "btn btn-primary form-button-create" %>
    <% end %>
  </div>
</div>

app/views/task_entries/show.html.erb
<div class="resource-container">
  <h1>Task Entry</h1>
    <div class="resource-info">
      <ul>
        <li>Task Entry Note: <%= @task_entry.note %></li>
        <li>Start Time: <%= @task_entry.start_time %></li>
        <li>Duration: <%= @task_entry.duration %> minutes</li>
      </ul>  
    </div>
    <div>
      <a href="/task_entries/<%=@task_entry.id %>/edit" class="btn btn-primary">Edit</a>
      <%= link_to "delete", 
        @Task_Entry, 
        method: :delete, 
        data: { confirm: "You sure?" }, 
        class: ["btn","btn-primary"] %>
    </div>
</div>