config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, :customers, :projects, :tasks
  resources :task_entries do 
    put '/start', to: 'task_entries#start_now'
    put '/stop', to: 'task_entries#stop_now'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :project_id, presence: true
  validates :user_id, presence: true
  validates :task_name, presence: true, length: { maximum: 500 }

  has_many :task_entries, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :logged_in_user 

    def initialize 
        super
        @resource = "Tasks"
        end

    # CREATE
    def create 
        @task = Task.new(task_params)
        if @task.save
            flash[:success] = "Created task"
            redirect_to @task
        else
            render :new
        end 
    end

    def new
        @task = Task.new if @task == nil
        @project_options = Project.all.map{|p|[p.project_name, p.id]}
        @user_options = User.all.map{|u|[u.username, u.id]}
    end

    # READ
    def index 
        @tasks = Task.where(user_id: current_user.id).paginate(page: params[:page], :per_page => 10)
    end

    def show 
        @task = Task.find(params[:id])
        @task_entries = @task.task_entries
        @project = @task.project_id
        @user = @task.user_id
    end

    # UPDATE
    def update
        @task = Task.find(params[:id])
        if @task.update_attributes(task_params)
            flash[:success] = "Updated task"
            redirect_to @task
        else
            render 'edit'
        end
    end

    def edit 
        @task = Task.find(params[:id])
    end 

    # DESTROY
    def destroy
        Task.find(params[:id]).destroy
        flash[:success] = "Deleted task"
        redirect_to tasks_url
    end

    private 
    def task_params 
        params.require(:task).permit(:project_id, :user_id, :task_name)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>">
    <span class="task_name">
        <a href="/tasks/<%= task.id %>">
            <%= task.task_name %>
        </a>
    </span>
</li>

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>
<h1>Edit Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task) do |f| %>
      <%= render 'shared/error_messages', :@profile => @task %>

      <%= f.label :task_name %>
      <%= f.text_field :task_name, class: 'form-control'%>

      <%= f.submit "Save changes", class: "btn btn-primary form-button-create" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, 'Tasks') %>
<div class="container resources-container">
  <h1>Tasks</h1>
  <%= render 'shared/paginate', :@profile => @tasks%>
    <ul class="resources">
      <% @tasks.each do |task| %>
        <li>
          <%= link_to task.task_name, task %>
        </li>
      <% end %>
    </ul>
  <%= render 'shared/paginate', :@profile => @tasks%>
  <div class="center">
    <%= link_to "Create Task", new_task_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/tasks/new.html.erb
<% provide(:title, 'Create Task') %>
<h1>Create Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@task) do |f| %>
      <%= render 'shared/error_messages', :@profile => @task %>

      <%= f.label :task_name %>
      <%= f.text_field :task_name, class: 'form-control'%>

      <%= f.label :project %>
      <%= f.select :project_id, Project.all.collect{|p|[p.project_name, p.id]}, {}, {:class => 'form-control'}%>

      <%= f.label :user %>
      <%= f.select :user_id, User.all.collect{|u|[u.username, u.id]}, {}, {:class => 'form-control'}%>

      <%= f.submit "Create task", class: "btn btn-primary form-button-create" %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="resource-container">
  <h1>Task</h1>
    <div class="resource-info">
      <ul>
        <li>Task Name: <%= @task.task_name %></li>
      </ul>
    </div>
    <div>
      <a href="/tasks/<%=@task.id %>/edit" class="btn btn-primary">Edit</a>
      <%= link_to "delete", 
        @Task, 
        method: :delete, 
        data: { confirm: "You sure?" }, 
        class: ["btn","btn-primary"] %>
    </div>

    <div>
      <% if @task.task_entries.any? %>
        <h3>Task Entries (<%= @task.task_entries.count %>)</h3>
        <ul class="partial-task_entries">
          <%= render @task_entries %>
        </ul>
      <% end %>
    </div>
    <%= link_to "Add Task Entry", new_task_entry_path, class: "btn btn-primary relationship-button-create" %>
</div>