config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, :customers, :projects, :tasks
  resources :task_entries do 
    put '/start', to: 'task_entries#start_now'
    put '/stop', to: 'task_entries#stop_now'
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :customer
  validates :customer_id, presence: true
  validates :project_name, presence: true, length: { maximum: 50 }

  has_many :tasks, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :logged_in_user

    def initialize
        super
        @resource = "Projects"
    end

    # CREATE
    def create
        @project = Project.new(project_params)
        if @project.save
            flash[:success] = "Created project"
            redirect_to @project
        else
            render :new
        end
    end

    def new
        @customer_options = Customer.all.map{|c|[c.company, c.id]}
        @project = Project.new if @project == nil
    end

    # READ
    def index
        @projects = Project.paginate(page: params[:page], :per_page => 10)
    end

    def show
        @project = Project.find(params[:id])
        @tasks = @project.tasks
    end

    # UPDATE
    def update
        @project = Project.find(params[:id])
        if @project.update_attributes(project_params)
            flash[:success] = "Updated project"
            redirect_to @project
        else
            render 'edit'
        end
    end

    def edit
        @project = Project.find(params[:id])
    end

    # DESTROY
    def destroy
        Project.find(params[:id]).destroy
        flash[:success] = "Deleted project"
        redirect_to projects_url
    end

    private
    def project_params
        params.require(:project).permit(:project_name, :customer_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<li id="project-<%= project.id %>">
    <span class="project_name">
        <a href="/projects/<%= project.id %>">
            <%= project.project_name %>
        </a>
    </span>
</li>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project') %>
<h1>Edit Project</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@project) do |f| %>
        <%= render 'shared/error_messages', :@profile => @project %>

        <%= f.label :project_name %>
        <%= f.text_field :project_name, class: 'form-control'%>

        <%= f.label :customer %>
        <%= f.select :customer_id, Customer.all.collect{|c|[c.company, c.id]}, {}, {:class => 'form-control'}%>

        <%= f.submit "Save changes", class: "btn btn-primary form-button-create" %>
        <% end %>
    </div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Projects') %>
<div class="container resources-container">
  <h1>Projects</h1>
  <%= render 'shared/paginate', :@profile => @projects%>
    <ul class="resources">
      <% @projects.each do |project| %>
        <li> 
          <%= link_to project.project_name, project %>
        </li>
      <% end %>
    </ul>
  <%= render 'shared/paginate', :@profile => @projects%>
  <div class="center">
    <%= link_to "Create Project", new_project_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'Create Project') %>
<h1>Create Project</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@project) do |f| %>
        <%= render 'shared/error_messages', :@profile => @project %>

        <%= f.label :project_name %>
        <%= f.text_field :project_name, class: 'form-control'%>

        <%= f.label :customer %>
        <%= f.select :customer_id, Customer.all.collect{|c|[c.company, c.id]}, {}, {:class => 'form-control'}%>

        <%= f.submit "Create project", class: "btn btn-primary form-button-create" %>
        <% end %>
    </div>
</div>

app/views/projects/show.html.erb
<div class="resource-container">
    <h1>Project</h1>
        <div class="resource-info">
            <ul>
                <li>Project: <%= @project.project_name %></li>
                <li>Customer: <%= @project.customer.company%></li>
            </ul>
        </div>
        <div>
            <a href="/projects/<%=@project.id %>/edit" class="btn btn-primary">Edit</a>
            <%= link_to "delete", 
                @Project, 
                method: :delete, 
                data: { confirm: "You sure?" }, 
                class: ["btn","btn-primary"] 
            %>
        </div>
        <div>
            <% if @project.tasks.any? %>
                <h3>Tasks (<%= @project.tasks.count %>)</h3>
                <ul class="partial-tasks">
                <%= render @tasks %>
                </ul>
            <% end %>
        </div>
    <%= link_to "Add Task", new_task_path, class: "btn btn-primary relationship-button-create" %>
</div>