config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, :customers, :projects, :tasks
  resources :task_entries do 
    put '/start', to: 'task_entries#start_now'
    put '/stop', to: 'task_entries#stop_now'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer center">
    <ul class="">
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Customers", customers_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Tasks", tasks_path %></li>
        <li><%= link_to "Task Entries", task_entries_path %></li>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Rails App", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <%= @resource%> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Users", users_path %></li>
                            <li><%= link_to "Customers", customers_path %></li>
                            <li><%= link_to "Projects", projects_path %></li>
                            <li><%= link_to "Tasks", tasks_path %></li>
                            <li><%= link_to "Task Entries", task_entries_path %></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Profile", current_user %></li>
                            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                            <li class="divider"></li>
                            <li>
                                <%= link_to "Log out", logout_path, method: :delete %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Log in", login_path %>
                    </li>
                <% end %>
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>
            <%= full_title(yield(:title)) %>
        </title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= render 'layouts/shim' %>
    </head>
    <body>
        <%= render 'layouts/header' %>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
        </div>
        <% if logged_in? %>
            <%= render 'layouts/footer' %>
        <% end %>
    </body>
</html>